import React from "react";
import { Document, Page, View, Text } from "@react-pdf/renderer";
import { styles as s, BUYER } from "./theme.js";

const Row = ({ label, value, last }) => (
  <View style={last ? s.rowLast : s.row}>
    <Text style={s.cellL}>{label}</Text>
    <Text style={s.cellR}>{value}</Text>
  </View>
);

const Clause = ({ children }) => (
  <View style={s.clause}>
    <Text style={s.bullet}>•</Text>
    <Text style={s.clauseText}>{children}</Text>
  </View>
);

/**
 * Cash LOI. `d` is a merge-field object from buildExportRow() (SALVO_BUILD.md §7.2).
 */
export default function CashLOI({ d }) {
  const where = [d.City, d.State].filter(Boolean).join(", ");
  return (
    <Document title={`Cash LOI — ${d.Address}`} author="Salvo">
      <Page size="LETTER" style={s.page}>
        <View style={s.headRow}>
          <View>
            <Text style={s.brand}>SALVO</Text>
            <Text style={s.tag}>fire the whole list</Text>
          </View>
          <View style={s.buyerBlock}>
            <Text style={s.buyerName}>BrightPath Real Estate Solutions, LLC</Text>
            <Text style={s.meta}>{d.Date}</Text>
          </View>
        </View>
        <View style={s.rule} />

        <Text style={s.title}>Letter of Intent — Cash Offer</Text>
        <Text style={s.subtitle}>Non-binding all-cash offer to purchase real property</Text>

        <View style={s.recipient}>
          <Text style={s.label}>Presented to</Text>
          <Text style={s.strong}>{d["Contact Name"] || "Property Owner"}{d["Contact Type"] ? `  (${d["Contact Type"]})` : ""}</Text>
          <Text style={s.label}>Regarding property</Text>
          <Text style={s.strong}>{d.Address}{where ? `, ${where}` : ""}</Text>
        </View>

        <Text style={s.para}>
          On behalf of {BUYER}, we submit this non-binding all-cash Letter of Intent to
          purchase the property from {d["Owner Full Name"] || "the seller"}, subject to a
          mutually executed purchase agreement.
        </Text>

        <Text style={s.sectionHead}>Proposed Terms</Text>
        <View style={s.table}>
          <Row label="Cash Purchase Price" value={d["Cash Scenario"]} />
          <Row label="Net Cash to Seller" value={d["Net Cash"]} />
          <Row label="Estimated Selling Costs Avoided" value={d["Industry Costs"]} last />
        </View>

        <Text style={s.sectionHead}>Key Conditions</Text>
        <Clause>All-cash purchase — no financing contingency.</Clause>
        <Clause>14-day inspection / due-diligence period.</Clause>
        <Clause>30-day (or faster) close following execution of the purchase agreement.</Clause>
        <Clause>Earnest money deposit of 1% of the purchase price.</Clause>
        <Clause>Property purchased in as-is, where-is condition.</Clause>

        <View style={s.sign}>
          <Text>Respectfully,</Text>
          <Text style={s.signLine}>{BUYER}</Text>
        </View>

        <Text style={s.footer} fixed>
          This Letter of Intent is non-binding and does not constitute a contract. Generated by Salvo for {BUYER}.
        </Text>
      </Page>
    </Document>
  );
}
