import React from "react";
import { Document, Page, View, Text } from "@react-pdf/renderer";
import { styles as s, C, BUYER } from "./theme.js";

const Row = ({ label, value, last }) => (
  <View style={last ? s.rowLast : s.row}>
    <Text style={s.cellL}>{label}</Text>
    <Text style={s.cellR}>{value}</Text>
  </View>
);

const Clause = ({ children }) => (
  <View style={s.clause}>
    <Text style={s.bullet}>•</Text>
    <Text style={s.clauseText}>{children}</Text>
  </View>
);

/**
 * Creative LOI (Subject-To + Seller Finance). `d` is a merge-field object as
 * produced by buildExportRow() in ../engine.js (keys are the exact LOI merge
 * tags from SALVO_BUILD.md §7.1).
 */
export default function CreativeLOI({ d }) {
  const where = [d.City, d.State].filter(Boolean).join(", ");
  return (
    <Document title={`Creative LOI — ${d.Address}`} author="Salvo">
      <Page size="LETTER" style={s.page}>
        <View style={s.headRow}>
          <View>
            <Text style={s.brand}>SALVO</Text>
            <Text style={s.tag}>fire the whole list</Text>
          </View>
          <View style={s.buyerBlock}>
            <Text style={s.buyerName}>BrightPath Real Estate Solutions, LLC</Text>
            <Text style={s.meta}>{d.Date}</Text>
          </View>
        </View>
        <View style={s.rule} />

        <Text style={s.title}>Letter of Intent — Seller Finance / Subject-To</Text>
        <Text style={s.subtitle}>Non-binding offer to purchase real property on creative terms</Text>

        <View style={s.recipient}>
          <Text style={s.label}>Presented to</Text>
          <Text style={s.strong}>{d["Contact Name"] || "Property Owner"}{d["Contact Type"] ? `  (${d["Contact Type"]})` : ""}</Text>
          <Text style={s.label}>Regarding property</Text>
          <Text style={s.strong}>{d.Address}{where ? `, ${where}` : ""}</Text>
        </View>

        <Text style={s.para}>
          On behalf of {BUYER}, we submit this non-binding Letter of Intent to purchase the
          property from {d["Owner Full Name"] || "the seller"} on a seller-financed /
          subject-to basis, subject to a mutually executed purchase agreement.
        </Text>

        <Text style={s.sectionHead}>Proposed Terms</Text>
        <View style={s.table}>
          <Row label="Purchase Price" value={d.Price} />
          <Row label="Existing Loan Balance" value={d["Loan Balance"]} />
          <Row label="Down Payment at Closing" value={d.Down} />
          <Row label="Seller-Financed Amount" value={d.Financed} />
          <Row label="Monthly Payment to Seller" value={d.Payment} />
          <Row label="Existing Loan Payment (paid via servicer)" value={d["Sub Payment"]} />
          <Row label="Interest" value="Built-Into Purchase Price" />
          <Row label="Balloon" value="To be Determined (TBD)" last />
        </View>

        <View style={s.hook}>
          <Text style={s.hookLabel}>The Seller Finance Difference</Text>
          <Text style={s.hookBig}>{d["Seller Profit Difference"]} more in your pocket</Text>
          <Text style={s.hookSub}>
            Selling creatively nets {d["Seller Profit Creative"]} versus {d["Seller Profit Traditional"]} on a
            traditional MLS sale after an estimated {d["Industry Costs"]} in selling costs.
          </Text>
        </View>

        <Text style={s.sectionHead}>Key Conditions</Text>
        <Clause>14-day inspection / due-diligence period.</Clause>
        <Clause>30-day close following execution of the purchase agreement.</Clause>
        <Clause>Earnest money deposit of 1% of the purchase price.</Clause>
        <Clause>Up to 3% agent commission honored where applicable.</Clause>
        <Clause>Property purchased in as-is, where-is condition.</Clause>

        <View style={s.sign}>
          <Text>Respectfully,</Text>
          <Text style={s.signLine}>{BUYER}</Text>
        </View>

        <Text style={s.footer} fixed>
          This Letter of Intent is non-binding and does not constitute a contract. Generated by Salvo for {BUYER}.
        </Text>
      </Page>
    </Document>
  );
}
