/** Creative + Cash LOI templates as react-pdf components (spec §7). */
import { Document, Page, StyleSheet, Text, View } from "@react-pdf/renderer";
import { BUYER_ENTITY, type LOIFields } from "@/lib/engine/loi";
import type { Offer } from "@/lib/engine/types";

const C = {
  ink: "#1b2228",
  ink2: "#4a5560",
  line: "#d6dbe0",
  gold: "#e86a2a",
  goldSoft: "#fbe7da",
  steel: "#356886",
  gain: "#147a54",
};

const st = StyleSheet.create({
  page: { paddingTop: 40, paddingBottom: 48, paddingHorizontal: 54, fontSize: 10, fontFamily: "Helvetica", color: C.ink, lineHeight: 1.4 },
  band: { borderBottomWidth: 2, borderBottomColor: C.gold, paddingBottom: 8, marginBottom: 12, flexDirection: "row", justifyContent: "space-between", alignItems: "flex-end" },
  brand: { fontSize: 14, fontFamily: "Helvetica-Bold", letterSpacing: 2 },
  brandSub: { fontSize: 8, color: C.ink2, marginTop: 2 },
  docTitle: { fontSize: 10, fontFamily: "Helvetica-Bold", color: C.steel, letterSpacing: 1.5, textTransform: "uppercase" },
  meta: { marginBottom: 10 },
  metaRow: { flexDirection: "row", marginBottom: 2 },
  metaKey: { width: 52, fontFamily: "Helvetica-Bold", color: C.ink2, fontSize: 9 },
  metaVal: { fontSize: 10 },
  p: { marginBottom: 8, textAlign: "justify" },
  h: { fontSize: 9, fontFamily: "Helvetica-Bold", color: C.ink2, letterSpacing: 1.2, textTransform: "uppercase", marginBottom: 5, marginTop: 4 },
  table: { borderWidth: 1, borderColor: C.line, borderRadius: 4, marginBottom: 10 },
  row: { flexDirection: "row", borderBottomWidth: 1, borderBottomColor: C.line, paddingVertical: 3, paddingHorizontal: 10 },
  rowLast: { borderBottomWidth: 0 },
  cellKey: { flex: 1.4, color: C.ink2 },
  cellVal: { flex: 1, textAlign: "right", fontFamily: "Helvetica-Bold" },
  diffBox: { backgroundColor: C.goldSoft, borderLeftWidth: 3, borderLeftColor: C.gold, padding: 9, marginBottom: 10 },
  diffTitle: { fontSize: 9, fontFamily: "Helvetica-Bold", color: "#b3560f", letterSpacing: 1.2, textTransform: "uppercase", marginBottom: 5 },
  diffRow: { flexDirection: "row", justifyContent: "space-between", marginBottom: 2 },
  diffKey: { color: "#7a3d12", fontSize: 9.5 },
  diffVal: { fontFamily: "Helvetica-Bold", fontSize: 9.5, color: "#7a3d12" },
  diffHero: { flexDirection: "row", justifyContent: "space-between", marginTop: 5, paddingTop: 5, borderTopWidth: 1, borderTopColor: "#eac9ae" },
  diffHeroKey: { fontFamily: "Helvetica-Bold", color: C.gold, fontSize: 11 },
  diffHeroVal: { fontFamily: "Helvetica-Bold", color: C.gold, fontSize: 11 },
  fine: { fontSize: 8, color: C.ink2, marginBottom: 6, textAlign: "justify" },
  sig: { marginTop: 10, flexDirection: "row", justifyContent: "space-between" },
  sigCol: { width: "45%" },
  sigLine: { borderBottomWidth: 1, borderBottomColor: C.ink, height: 22, marginBottom: 4 },
  sigLbl: { fontSize: 8, color: C.ink2 },
  foot: { position: "absolute", bottom: 26, left: 54, right: 54, borderTopWidth: 1, borderTopColor: C.line, paddingTop: 6, fontSize: 7.5, color: C.ink2, textAlign: "center" },
});

function Band({ title }: { title: string }) {
  return (
    <View style={st.band}>
      <View>
        <Text style={st.brand}>BRIGHTPATH</Text>
        <Text style={st.brandSub}>BrightPath Real Estate Solutions, LLC</Text>
      </View>
      <Text style={st.docTitle}>{title}</Text>
    </View>
  );
}

function Meta({ f }: { f: LOIFields }) {
  return (
    <View style={st.meta}>
      <View style={st.metaRow}><Text style={st.metaKey}>Date</Text><Text style={st.metaVal}>{f.date}</Text></View>
      <View style={st.metaRow}><Text style={st.metaKey}>To</Text><Text style={st.metaVal}>{f.ownerFullName}</Text></View>
      <View style={st.metaRow}><Text style={st.metaKey}>Re</Text><Text style={st.metaVal}>{f.address}</Text></View>
    </View>
  );
}

function Row({ k, v, last = false }: { k: string; v: string; last?: boolean }) {
  return (
    <View style={last ? [st.row, st.rowLast] : st.row}>
      <Text style={st.cellKey}>{k}</Text>
      <Text style={st.cellVal}>{v}</Text>
    </View>
  );
}

function Footer() {
  return (
    <Text style={st.foot} fixed>
      {BUYER_ENTITY} · This Letter of Intent is non-binding and is an invitation to negotiate only. Generated by Salvo.
    </Text>
  );
}

/** Creative LOI — Subject-To + Seller Finance (spec §7.1). */
export function CreativeLOIPage({ f }: { f: LOIFields }) {
  return (
    <Page size="LETTER" style={st.page}>
      <Band title="Letter of Intent · Seller Finance" />
      <Meta f={f} />
      <Text style={st.p}>
        Dear {f.ownerFullName}, {BUYER_ENTITY} (&quot;Buyer&quot;) is pleased to submit this Letter of Intent to purchase the
        property referenced above on the seller-finance terms below. This structure lets you sell at your price — the
        interest is built into the purchase price — while avoiding the roughly {f.industryCosts} in industry selling
        costs a traditional MLS sale would take out of your proceeds.
      </Text>

      <Text style={st.h}>Proposed Terms</Text>
      <View style={st.table}>
        <Row k="Purchase Price" v={f.price} />
        <Row k="Down Payment" v={f.down} />
        <Row k="Existing Loan Balance (taken Subject-To)" v={f.loanBalance} />
        <Row k="Seller-Financed Balance" v={f.financed} />
        <Row k="Monthly Payment to Seller" v={f.payment} />
        <Row k="Existing Loan Payment (paid via licensed servicer)" v={f.subPayment} />
        <Row k="Interest" v="Built-Into Purchase Price" />
        <Row k="Balloon" v="To be Determined (TBD)" />
        <Row k="Earnest Money Deposit" v="1% of Purchase Price" />
        <Row k="Inspection Period" v="14 days" />
        <Row k="Closing" v="On or before 30 days" />
        <Row k="Agent Compensation" v="Up to 3%" last />
      </View>

      <View style={st.diffBox}>
        <Text style={st.diffTitle}>The Seller Finance Difference</Text>
        <View style={st.diffRow}><Text style={st.diffKey}>Estimated Home Value</Text><Text style={st.diffVal}>{f.homeValue}</Text></View>
        <View style={st.diffRow}><Text style={st.diffKey}>Industry Selling Costs (agent fees, concessions, holding)</Text><Text style={st.diffVal}>- {f.industryCosts}</Text></View>
        <View style={st.diffRow}><Text style={st.diffKey}>Estimated Net — Traditional MLS Sale</Text><Text style={st.diffVal}>{f.sellerProfitTraditional}</Text></View>
        <View style={st.diffRow}><Text style={st.diffKey}>Estimated Net — This Seller-Finance Offer</Text><Text style={st.diffVal}>{f.sellerProfitCreative}</Text></View>
        <View style={st.diffHero}><Text style={st.diffHeroKey}>You net more by selling creatively</Text><Text style={st.diffHeroVal}>+{f.sellerProfitDifference}</Text></View>
      </View>

      <Text style={st.fine}>
        Property to be purchased in as-is condition. Buyer to verify all figures during the inspection period. This
        Letter of Intent is an expression of interest only; neither party is bound until a definitive purchase agreement
        is executed by both parties. Existing financing to remain in place and be serviced through a licensed loan
        servicing company.
      </Text>

      <View style={st.sig} wrap={false}>
        <View style={st.sigCol}>
          <View style={st.sigLine} />
          <Text style={st.sigLbl}>Buyer · {BUYER_ENTITY}</Text>
        </View>
        <View style={st.sigCol}>
          <View style={st.sigLine} />
          <Text style={st.sigLbl}>Seller · {f.ownerFullName} · Date</Text>
        </View>
      </View>
      <Footer />
    </Page>
  );
}

/** Cash LOI (spec §7.2). */
export function CashLOIPage({ f }: { f: LOIFields }) {
  return (
    <Page size="LETTER" style={st.page}>
      <Band title="Letter of Intent · Cash Offer" />
      <Meta f={f} />
      <Text style={st.p}>
        Dear {f.ownerFullName}, {BUYER_ENTITY} (&quot;Buyer&quot;) is pleased to submit this all-cash Letter of Intent for the
        property referenced above. No financing contingency, no repairs, no showings — a certain close on your timeline.
      </Text>

      <Text style={st.h}>Proposed Terms</Text>
      <View style={st.table}>
        <Row k="Cash Purchase Price" v={f.cashScenario} />
        <Row k="Estimated Net Cash to Seller (after existing loan payoff)" v={f.netCash} />
        <Row k="Industry Selling Costs You Avoid" v={f.industryCosts} />
        <Row k="Earnest Money Deposit" v="1% of Purchase Price" />
        <Row k="Inspection Period" v="14 days" />
        <Row k="Closing" v="On or before 30 days" last />
      </View>

      <Text style={st.fine}>
        Property to be purchased in as-is condition; Buyer pays standard buyer-side closing costs. This Letter of Intent
        is an expression of interest only; neither party is bound until a definitive purchase agreement is executed by
        both parties.
      </Text>

      <View style={st.sig} wrap={false}>
        <View style={st.sigCol}>
          <View style={st.sigLine} />
          <Text style={st.sigLbl}>Buyer · {BUYER_ENTITY}</Text>
        </View>
        <View style={st.sigCol}>
          <View style={st.sigLine} />
          <Text style={st.sigLbl}>Seller · {f.ownerFullName} · Date</Text>
        </View>
      </View>
      <Footer />
    </Page>
  );
}

export interface LOIEntry {
  f: LOIFields;
  creativeOK: boolean;
  cashOK: boolean;
}

/**
 * One document for the whole selection. Creative sends can carry the cash page
 * along (the current .docx behavior) — configurable via `includeCashPage`.
 */
export function LOIDocument({ entries, offer, includeCashPage }: {
  entries: LOIEntry[];
  offer: Offer;
  includeCashPage: boolean;
}) {
  return (
    <Document title="Salvo LOIs" author={BUYER_ENTITY}>
      {entries.flatMap((e, i) => {
        const pages = [];
        const wantCreative = offer !== "cash" && e.creativeOK;
        const wantCash =
          offer === "cash" ? e.cashOK
          : offer === "both" ? e.cashOK
          : includeCashPage && e.cashOK;
        if (wantCreative) pages.push(<CreativeLOIPage key={`cr-${i}`} f={e.f} />);
        if (wantCash) pages.push(<CashLOIPage key={`ca-${i}`} f={e.f} />);
        return pages;
      })}
    </Document>
  );
}
