import { StyleSheet } from "@react-pdf/renderer";

export const ORDNANCE = {
  ink: "#1b2228",
  ink2: "#4a5560",
  line: "#d6dbe0",
  gold: "#e86a2a",
  steel: "#356886",
  gain: "#147a54",
  canvas: "#eceef1",
};

export const pdfStyles = StyleSheet.create({
  page: {
    padding: 40,
    fontSize: 10,
    fontFamily: "Helvetica",
    color: ORDNANCE.ink,
  },
  headerRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: 18,
    borderBottomWidth: 2,
    borderBottomColor: ORDNANCE.gold,
    paddingBottom: 12,
  },
  wordmark: {
    fontSize: 18,
    fontFamily: "Helvetica-Bold",
    letterSpacing: 3,
    color: ORDNANCE.ink,
  },
  tagline: {
    fontSize: 8,
    color: ORDNANCE.ink2,
    marginTop: 2,
  },
  docTitle: {
    fontSize: 13,
    fontFamily: "Helvetica-Bold",
    textAlign: "right",
  },
  metaRight: {
    fontSize: 9,
    color: ORDNANCE.ink2,
    textAlign: "right",
    marginTop: 3,
  },
  section: { marginBottom: 14 },
  sectionTitle: {
    fontSize: 10,
    fontFamily: "Helvetica-Bold",
    color: ORDNANCE.steel,
    marginBottom: 6,
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  headline: {
    marginTop: 4,
    marginBottom: 14,
    padding: 12,
    backgroundColor: "#fdf1ea",
    borderWidth: 1,
    borderColor: ORDNANCE.gold,
    borderRadius: 4,
  },
  headlineLabel: {
    fontSize: 9,
    color: ORDNANCE.gold,
    fontFamily: "Helvetica-Bold",
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  headlineValue: {
    fontSize: 20,
    fontFamily: "Helvetica-Bold",
    color: ORDNANCE.gold,
    marginTop: 2,
  },
  grid: {
    flexDirection: "row",
    flexWrap: "wrap",
  },
  cell: {
    width: "50%",
    flexDirection: "row",
    justifyContent: "space-between",
    paddingVertical: 4,
    paddingRight: 10,
    borderBottomWidth: 1,
    borderBottomColor: ORDNANCE.line,
  },
  cellLabel: { color: ORDNANCE.ink2 },
  cellValue: { fontFamily: "Helvetica-Bold" },
  paragraph: { fontSize: 9, color: ORDNANCE.ink2, lineHeight: 1.5, marginBottom: 6 },
  clauseList: { marginTop: 4 },
  clauseItem: { fontSize: 9, color: ORDNANCE.ink2, marginBottom: 3, lineHeight: 1.4 },
  footer: {
    position: "absolute",
    bottom: 30,
    left: 40,
    right: 40,
    fontSize: 8,
    color: ORDNANCE.ink2,
    borderTopWidth: 1,
    borderTopColor: ORDNANCE.line,
    paddingTop: 8,
  },
});
